Artistwala_BB/ArtistWala/Models/ArtistOverviewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ArtistWala.Models
{
    /// <summary>
    /// /this is for artist over view
    /// </summary>
    public class ArtistOverviewModel
    {
        public int OverviewId { get; set; }
        public int ArtistId { get; set; }
        public string WhatToExpect { get; set; }
        public string Influence { get; set; }
        public string Calender { get; set; }
        public string Personal { get; set; }
        public string Tesimonials { get; set; }
        public string SetUpRequirements { get; set; }
    }
}

Artistwala_BB/ArtistWala/Areas/Admin/Controllers/DashboardController.cs
using ArtistWala.Areas.Admin.Models;
using ArtistWala.Common;
using ArtistWala.Models;
using ArtistWala.Repository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ArtistWala.Areas.Admin.Controllers
{
    public class DashboardController : Controller
    {
        ArtistWalaEntities context = new ArtistWalaEntities();
        AESEncryption objEncrp = new AESEncryption();
        //
        // GET: /Admin/Home/
        [CustomAuthorization(LoginPage = "~/Admin/Dashboard/AdminLogin")]
        public ActionResult Index()
        {
            FormsIdentity frmTicket = (FormsIdentity)User.Identity;
            FormsAuthenticationTicket ticket = frmTicket.Ticket;
            int accountID = Convert.ToInt32(ticket.UserData);

            DashaboardModel obj = new DashaboardModel()
            {
                ArtistCount = context.tblArtists.Where(x => x.IsActive == true).Count(),
                MessageCount = context.tblUserMessages.Where(x => x.IsUnread == true && x.Fk_UserId == accountID).Count(),
                ApprovalRequestCount = context.tblArtists.Where(x => (x.IsActive ?? false) == false).Count(),
            };

            return View(obj);
        }

        [CustomAuthorization(LoginPage = "~/Admin/Dashboard/AdminLogin")]
        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();

            Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(-1));
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.Cache.SetNoStore();
            Session.Abandon();

            return RedirectToAction("AdminLogin", "Dashboard", new { Area = "Admin" });
        }

        public ActionResult AdminLogin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AdminLogin(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                String userName = model.UserName;
                String passward = objEncrp.EncryptPassword(model.Password);
                tblUser UserTbl = AuthenticateUser(userName, passward);
                if (UserTbl != null)
                {
                    if (UserTbl.FK_RoleId == 1 || UserTbl.FK_RoleId == 2)
                    {
                        model.Password = null;
                        model.Name = UserTbl.Name;
                        model.UserId = UserTbl.UserId;

                        model.RoleId = UserTbl.FK_RoleId;

                        Session[SessionConstants.RoleId] = UserTbl.FK_RoleId;

                        return GetUserAuthentication(model);
                    }
                    else
                    {
                        ViewBag.Message = "You are not authorized.";
                        return View(model);
                    }
                }
                else
                {
                    // If we got this far, something failed, redisplay form
                    ViewBag.Message = "Username / Password is incorrect";
                    return View(model);
                }
            }
            else
            {
                ViewBag.Message = "Please enter your Username / Password";
                // If we got this far, something failed, redisplay form
                return View(model);
            }
        }

        private tblUser AuthenticateUser(String userName, String userPassword)
        {
            return context.tblUsers.Where(x => x.UserName.Trim().ToUpper() == userName.Trim().ToUpper()
                                            && x.Password.Trim().ToUpper() == userPassword.Trim().ToUpper()
                                            && x.IsActive == true).FirstOrDefault();
        }
        private ActionResult GetUserAuthentication(LoginModel model)
        {

            FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(
            1, // Ticket version
            model.UserName,// Username to be associated with this ticket
            DateTime.Now, // Date/time ticket was issued
            DateTime.Now.AddHours(5), // Date and time the cookie will expire
            false, // if user has chcked rememebr me then create persistent cookie
            model.UserId.ToString(), // store the user data, in this case userId of the user
            FormsAuthentication.FormsCookiePath); // Cookie path specified in the web.config file in <Forms> tag if any.

            // To give more security it is suggested to hash it
            string hashCookies = FormsAuthentication.Encrypt(ticket);
            HttpCookie cookie = new HttpCookie(FormsAuthentication.FormsCookieName, hashCookies); // Hashed ticket

            Session[ArtistWala.Models.SessionConstants.UserProfileObject] = model;

            // Add the cookie to the response, user browser
            Response.Cookies.Add(cookie);
            string ReturnUrl = Convert.ToString(Session["ReturnUrl"]);

            if (!string.IsNullOrEmpty(ReturnUrl))
            {
                //ReturnUrl = ReturnUrl.Replace("/", "");
                return Redirect(ReturnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Dashboard", new { Area = "Admin" });
            }
        }

    }
}

Artistwala_BB/ArtistWala/Controllers/MyProfileController.cs
using ArtistWala.Areas.Admin.Models;
using ArtistWala.Common;
using ArtistWala.Models;
using ArtistWala.Repository;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;

namespace ArtistWala.Controllers
{
    [Authorize]
    public class MyProfileController : Controller
    {
        ArtistWalaEntities context = new ArtistWalaEntities();
        AESEncryption objEncrp = new AESEncryption();
        CommonMethods objCommon = new CommonMethods();
        //
        // GET: /MyProfile/

        #region JSONAJAX
        public JsonResult SendReplayMessage(string id, string MessageBody)
        {
            SMSCAPI oSMS = new SMSCAPI();
            
            tblUserMessage oMessages = new tblUserMessage();
            int MessageId = Convert.ToInt32(id);
            var MessageDetails = context.tblUserMessages.Where(x => x.MessageId == MessageId).Select(s => s).FirstOrDefault();
            if (MessageDetails != null)
            {
                oMessages.SendBy = MessageDetails.Fk_UserId;
                oMessages.Fk_UserId = MessageDetails.SendBy;
                oMessages.MessageBody = MessageBody;
                oMessages.MessageType = MessageDetails.MessageType;
                oMessages.MessageSubject = MessageDetails.MessageSubject;
                oMessages.IsUnread = true;
                oMessages.MessageDate = System.DateTime.Now;
                oMessages.MessageParentId = MessageDetails.MessageId;
                context.tblUserMessages.Add(oMessages);
                context.SaveChanges();

                //send mail and message to reciver
                var MobileNoTo = context.tblClients.Where(s => s.FK_UserId == MessageDetails.SendBy).Select(s => s).FirstOrDefault();
                tblSMSTemplate SMSTo = context.tblSMSTemplates.Where(x => x.TemplateId == 5).FirstOrDefault();
                string MessageBodyTo = SMSTo.SMSBody.Replace("@Name", MobileNoTo.ClientName);
                oSMS.SendSMS(MobileNoTo.ContactNo.ToString(), MessageBodyTo);
                tblEmailTemplate emailTo = context.tblEmailTemplates.Where(x => x.TemplateId == 14).FirstOrDefault();
                string emailBodyTo = emailTo.EmailBody.Replace("@Name", MobileNoTo.ClientName);
                objCommon.sendMailInHtmlFormat(emailTo.AddCC, MobileNoTo.Email, emailTo.AddBCC, emailTo.EmailSubject, emailBodyTo);

                //send mail and message to sender
                var MobileNofrom = context.tblClients.Where(s => s.FK_UserId == MessageDetails.Fk_UserId).Select(s => s).FirstOrDefault();
                tblSMSTemplate SMSFrom = context.tblSMSTemplates.Where(x => x.TemplateId == 6).FirstOrDefault();
                string MessageBodyFrom = SMSFrom.SMSBody.Replace("@Name", MobileNofrom.ClientName);
                oSMS.SendSMS(MobileNofrom.ContactNo.ToString(), MessageBodyFrom);
                tblEmailTemplate emailFrom = context.tblEmailTemplates.Where(x => x.TemplateId == 15).FirstOrDefault();
                string emailBodyFrom = emailFrom.EmailBody.Replace("@Name", MobileNofrom.ClientName);
                objCommon.sendMailInHtmlFormat(emailFrom.AddCC, MobileNofrom.Email, emailFrom.AddBCC, emailFrom.EmailSubject, emailBodyFrom);


            }
            else
            {
                ViewBag.errorMessage = "Something is wrong!";
            }
            return Json("Success");
        }
        #endregion
        public ActionResult Dashboard()
        {
            string SendByName = string.Empty;
            string SendByPic = string.Empty;
            string ReplayByNmae = string.Empty;
            LoginModel objLogin = objCommon.GetLoginDetails();
            List<MessageModel> objUserMessage = context.tblUserMessages.Where(x => x.Fk_UserId == objLogin.UserId).Select(s => new MessageModel
            {
                Fk_UserId = s.Fk_UserId,
                MessageBody = s.MessageBody,
                IsUnread = s.IsUnread,
                MessageDate = s.MessageDate,
                MessageId = s.MessageId,
                MessageParentId = s.MessageParentId,
                MessageSubject = s.MessageSubject,
                MessageType = s.MessageType,
                SendBy = s.SendBy,
                SendByPic = SendByPic + context.tblUsers.Where(x => x.UserId == s.SendBy).Select(u => u.ProfileImage).FirstOrDefault(),
                ReplyByPic = s.tblUser.ProfileImage,
                tblUser = s.tblUser,
                ReplayList = context.tblUserMessages.Where(p => p.MessageParentId != null && s.MessageId == p.MessageParentId).Select(v => v).OrderByDescending(o => o.MessageDate).ToList(),
            }).OrderByDescending(o => o.MessageId).ToList();
            if (objUserMessage.Count > 0)
            {
                foreach (var item in objUserMessage)
                {
                    SendByName = SendByName + context.tblUsers.Where(x => x.UserId == item.SendBy).Select(s => s.Name).FirstOrDefault() + ",";
                    if (item.ReplayList.Count > 0)
                    {
                        foreach (var reply in item.ReplayList)
                        {
                            ReplayByNmae = ReplayByNmae + context.tblUsers.Where(x => x.UserId == reply.SendBy).Select(s => s.Name).FirstOrDefault() + ",";
                        }
                        ViewBag.ReplayByNmae = ReplayByNmae;
                    }
                    else
                    {
                        ViewBag.ReplayByNmae = ReplayByNmae;
                    }
                }
                ViewBag.SendByName = SendByName;
            }
            else
            {
                ViewBag.SendByName = SendByName;
            }
            return View(objUserMessage);
        }

        public ActionResult LogOff()
        {
            FormsAuthentication.SignOut();

            Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(-1));
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.Cache.SetNoStore();
            Session.Abandon();

            return RedirectToAction("Index", "Home");
        }

        public ActionResult AddYourPicture()
        {
            LoginModel objLogin = objCommon.GetLoginDetails();
            tblUser objUser = context.tblUsers.Where(x => x.UserId == objLogin.UserId).FirstOrDefault();
            ViewBag.CurrentImage = ConfigurationManager.AppSettings["ArtistImagePath"] + objUser.ProfileImage;
            return View();
        }

        [HttpPost]
        public ActionResult AddYourPicture(FormCollection fC)
        {
            try
            {
                //if (!string.IsNullOrEmpty(fC["hidCoordinates"]))
                if (!string.IsNullOrEmpty(fC["hidCoordinates"]) && !Convert.ToString(fC["hidCoordinates"]).Equals("NaN|NaN|NaN|NaN"))
                {
                    LoginModel objLogin = objCommon.GetLoginDetails();

                    //fC["X"]
                    ///int xAxis = Convert.ToInt32(fC["X"].ToString());
                    int xAxis = Convert.ToInt32(fC["hidCoordinates"].Split('|')[0]);
                    int yAxis = Convert.ToInt32(fC["hidCoordinates"].Split('|')[1]);
                    int width = Convert.ToInt32(fC["hidCoordinates"].Split('|')[2]);
                    int height = Convert.ToInt32(fC["hidCoordinates"].Split('|')[3]);



                    Bitmap profImage = (Bitmap)Bitmap.FromFile(Convert.ToString(Session[SessionConstants.ProfilImage]));
                    Bitmap CroppedImage = CommonMethods_bak.CropImage(profImage, xAxis, yAxis, width, height);
                    string Name = Guid.NewGuid() + ".jpg";

                    profImage.Dispose();

                    var path = Path.Combine(Server.MapPath("~" + ConfigurationManager.AppSettings["ArtistImagePath"]), Name);

                    if (!System.IO.File.Exists(path))
                    {
                        CroppedImage.Save(path, System.Drawing.Imaging.ImageFormat.Jpeg);
                        System.IO.File.Delete(Convert.ToString(Session[SessionConstants.ProfilImage]));
                    }

                    if (!context.tblUsers.Any(x => x.UserId == objLogin.UserId))
                    {
                        tblUser objUser = new tblUser()
                        {
                            ProfileImage = Name,
                            IsHoldRights = Convert.ToBoolean(fC["image_ownership"] ?? "false")
                        };

                        context.tblUsers.Add(objUser);
                        context.SaveChanges();

                        ViewBag.Message = "Your profile image is added.";
                    }
                    else
                    {
                        tblUser objUser = context.tblUsers.Where(x => x.UserId == objLogin.UserId).FirstOrDefault();

                        objUser.ProfileImage = Name;
                        objUser.IsHoldRights = true;

                        context.Entry(objUser).State = EntityState.Modified;
                        context.SaveChanges();

                        ViewBag.Message = "Your profile image is updated.";
                    }

                    objLogin.ProfileImage = Name;
                    Session[SessionConstants.UserProfileObject] = objLogin;
                }
                else
                {
                    string Name = SaveImagesinServer("FILE2");
                    ViewBag.Image = ConfigurationManager.AppSettings["ArtistImagePath"] + Name;
                }
            }
            catch (Exception ex)
            {
                throw ex;
                //ViewBag.Message =  "Sorry! Please try again later.";
            }

            return View();
        }

        [HttpGet]
        public ActionResult AddCoverPicture()
        {

Artistwala_BB/ArtistWala/Views/MyProfile/AddPhotos.cshtml
@{
    ViewBag.Title = "Add Photos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $('#btnSave').click(function () {
        if ($('#image_caption').val() == '') {
            $('#reqImageTitle').show();
            return false;
        } else if ($('#image_ownership').is(':checked') == true) {
            $('#reqIowned').show();
            return false;
        }
        else {
            return true;
        }
    });
</script>

@using (Html.BeginForm("AddPhotos", "MyProfile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="totalContentdashboard">
        <div class="wrapper">
            <div class="dashboard_white">
                <div class="orannge_b"></div>
                <div class="orannge_heading"> You are here: </div>
                <div class="pagenatn">
                    <ul>
                        <li> Account Control Panel › </li>
                        <li style="color:#09577b"> @ViewBag.Title</li>
                    </ul>
                </div>
                <div class="clear"></div>


                <div class="location">
                    <h1><strong>Photo Gallery</strong></h1>
                    <div class="profile_bg">
                        <div class="photo_txt">
                            <div class="profile_bg_l">
                                Add multiple photos up to <strong>6MB </strong> each in size and <strong>jpg </strong>,
                                <strong>gif </strong>, or png formats only.
                                <!--As a free member, you may upload up to <strong>3</strong> photos. You currently have
                                <strong> 0.</strong>-->

                                <p style="margin-top:20px;">
                                    <label>Picture Caption *</label> <br />
                                    <input type="text" name="image_caption" id="image_caption" value="" class="text" maxlength="255">
                                    <span id="reqImageTitle" style="display:none;color:red;">
                                        Please enter your image title
                                    </span>
                                </p>

                                <input type="file" name="FILEPhoto" class="choose" id="FILEPhoto" multiple="multiple">
                                @ViewBag.Message <br />
                                <input type="checkbox" name="image_ownership" id="image_ownership" value="true">
                                <label> I own the rights to this photo, and it contains no trademarked characters, subjects or material owned by others.</label>
                                <span id="reqIowned" style="display:none;color:red;">
                                    Please select the above option
                                </span>
                                <div class="upload"> <input type="submit" id="btnSave" value="Save" /></div>
                            </div>
                            <p>We reserve the right to remove your photos and/or disable your PromoKit without notice if it violates our policies. Thank you in advance for your integrity.</p>
                        </div>
                        <div class="profile_bg_r">
                            <p>
                                <span> Please note:</span>

                                <strong>Do not upload photos containing trademarked material </strong> such as characters, subjects or material owned by others (for example, Disney characters).

                                <strong>Do not upload photos containing contact information</strong> such as website, email or phone. Your profile picture will be removed if it contains contact information.<!-- If you would like to post contact info, please consider upgrading to a
                                <a href="javascript:void(0);">Semi-Pro,</a> <a href="javascript:void(0);">Pro,</a> <a href="javascript:void(0);">or Featured membership</a>.--> Thanks!
                            </p>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="clear"></div>
                </div>
                <br />
                @{
    int i = 1;
    <table cellspacing="0" cellpadding="10" border="0" class="my-table table-layout-section thumb-icon">
                    <tr class="tr-head" style="font-weight:600;">
            <td>
                Image Title
            </td>
            <td>Image</td>
            <td>Action</td>
        </tr>
        @foreach (var item in Model)
        {
            if (item.FileType == "image")
            {
                string dvName = "dvImage" + i;
                string aName = "aImage" + i;
                <tr>
                    <td>
                        @item.Title
                    </td>
                    <td>
                        <a id="@aName" href="#@dvName">
                            @*@item.Title*@
                            <img src="@System.Configuration.ConfigurationManager.AppSettings["ArtistImagePath"]@item.FileName" alt="image">
                        </a>
                        <div id="@dvName" style="display:none;">
                            Image Title : @item.Title
                            <br />
                            @if (!string.IsNullOrEmpty(item.FileName) && System.IO.File.Exists(Server.MapPath(System.Configuration.ConfigurationManager.AppSettings["ArtistImagePath"] + item.FileName)))
                            {
                                <img src="@System.Configuration.ConfigurationManager.AppSettings["ArtistImagePath"]@item.FileName" alt="image">
                            }
                            else
                            {
                                <img src="~/images/no-image.png" alt="image">
                            }
                            <div class="clear"></div>
                        </div>
                        <script type="text/javascript">
                            $(function () {
                                $('#@aName').fancybox({
                                    'autoSize': false,
                                    'autoScale':true,
                                    'autoDimensions':true,
                                    
                                   helpers: { overlay: { closeClick: true } }
                                });
                            });
                        </script>
                    </td>
                    <td>
                        <a href="@Url.Action("DeletePhoto", "MyProfile", new { id = item.PortfolioId })">Delete</a>
                    </td>
                </tr>
                            i++;
            }
        }
    </table>
                }
            </div>
            <div class="clear"></div>
        </div>
    </div>
}

Artistwala_BB/ArtistWala/Views/MyProfile/AddYourPicture.mobile.cshtml
@*<script src="~/crop/js/jquery.min1.js"></script>*@

@{
    ViewBag.Title = "Add your picture";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<link href="~/crop/css/jquery.Jcrop.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3/jquery.min.js"></script>
    <script type="text/javascript" src="~/crop/js/jquery.Jcrop.js"></script>*@

<script src="/js/croper/jquery.Jcrop.js"></script>
<link rel="stylesheet" href="/js/croper/jquery.Jcrop.css" type="text/css" />


@*<script type="text/javascript">
        jQuery(document).ready(function () {
            jQuery('#imgCrop').Jcrop({
                onSelect: showCoords
            });
        });

        //function storeCoords(c) {
        //    jQuery('#X').val(c.x);
        //    jQuery('#Y').val(c.y);
        //    jQuery('#W').val(c.w);
        //    jQuery('#H').val(c.h);
        //};
        function showCoords(c) {
            $('#hidCoordinates').val(c.x + '|' + c.y + '|' + c.w + '|' + c.h);
            //$('#hidCoordinates').val('100 | 100 | 100 | 100');
        };

    </script>*@

@*<script type="text/javascript">

        jQuery(function ($) {
            var cropWidth = 100;
            var cropHeight = 100;
            var jcrop_api;

            $('#imgCrop').Jcrop({
                // start off with jcrop-light class
                //minSize: [500, 500],
                //maxSize: [800, 600],
                aspectRatio: 1,
                bgOpacity: 0.5,
                bgColor: 'black',
                addClass: 'jcrop-light',
                onChange: showCoords
            }, function () {
                jcrop_api = this;
                jcrop_api.setSelect([00, 00, 500, 500, 500, 500]);
                jcrop_api.setOptions({ bgFade: true });
                jcrop_api.ui.selection.addClass('jcrop-selection');
            });


        });
        jcrop_api.animateTo([0, 0, cropWidth, cropHeight]);
        function showCoords(c) {
            $('#hidCoordinates').val(c.x + '|' + c.y + '|' + c.w + '|' + c.h);
        };

    </script>*@


<script type="text/javascript">

    jQuery(function ($) {

        var jcrop_api;

        $('#imgCrop').Jcrop({
            aspectRatio: 1,
            onChange: showCoords
        }, function () {
            jcrop_api = this;
            jcrop_api.setSelect([350, 150, 500, 500, 500, 500]);
        });

    });

    function showCoords(c) {
        $('#hidCoordinates').val(c.x + '|' + c.y + '|' + c.w + '|' + c.h);
    };

</script>

@using (Html.BeginForm("AddYourPicture", "MyProfile", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="hidden" id="hidCoordinates" name="hidCoordinates" />

    @*<input type="hidden" id="X" name="hidCoordinates" />
        <input type="hidden" id="Y" />
        <input type="hidden" id="W"  />
        <input type="hidden" id="H" />*@

    <div class="totalContentdashboard">
        <div class="wrap">
            <div class="dashboard_white2">
                <div class="orannge_b"></div>
                <div class="orannge_heading"> You are here: </div>
                <div class="pagenatn">
                    <ul>
                        <li> Account Control Panel › </li>
                        <li style="color:#09577b"> @ViewBag.Title</li>
                    </ul>
                </div>
                <div class="clear"></div>


                <div class="location">
                    <h1><strong>Change Profile Picture</strong></h1>
                    <div class="profile_bg">
                        <div class="photo_txt">
                            <div class="profile_bg_l">
                                Add a photo up to <strong>4MB</strong> in size and <strong>jpg, gif,</strong> or<strong> png</strong> formats only.

                                <input name="FILE2" type="file" id="FILE2" class="choose" />

                                <input type="checkbox" name="image_ownership" id="image_ownership" value="true">
                                <label> I own the rights to this photo, and it contains no trademarked characters, subjects or material owned by others.</label>
                                <div class="upload"> <input type="submit" value="Upload" /></div>
                                <img style="margin-top:10px;" src="@ViewBag.Image" id="imgCrop">
                                <div class="upload" style="text-align:right;"> <input type="submit" value="Save" /></div>
                            </div>
                        </div>
                        <p>
                            @ViewBag.Message
                        </p>
                        <div class="profile_bg_r">

                        </div>
                        <div class="clear"></div>
                    </div>
                    <div></div>
                    <div class="clear"></div>
                </div>

            </div>
            <div class="clear"></div>
        </div>
    </div>
}

Artistwala_BB/ArtistWala/Views/MyProfile/ArtistOverview.cshtml
@model ArtistWala.Models.ArtistOverviewModel
@{
    ViewBag.Title = "Your Calender";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("ArtistOverview", "MyProfile", FormMethod.Post))
{
    <div class="totalContentdashboard">
        <div class="wrapper">
            <div class="dashboard_white">
                <div class="orannge_b"></div>
                <div class="orannge_heading"> You are here: </div>
                <div class="pagenatn">
                    <ul>
                        <li> Account Control Panel › </li>
                        <li style="color:#09577b"> @ViewBag.Title</li>
                    </ul>
                </div>
                <div class="clear"></div>

                <h1><strong>Add Your Overviews</strong> </h1>

                <div class="profile_pic_grey">

                    <dl>
                        <dt> <label for="image_title_hires">@Html.LabelFor(m => m.WhatToExpect, "What To Expect"):</label></dt>
                        <dd>@Html.TextAreaFor(m => m.WhatToExpect)</dd>
                        <dd>@Html.ValidationMessageFor(m => m.WhatToExpect)</dd>
                        <dd>&nbsp;</dd>

                        <dt> <label for="image_title_hires">@Html.LabelFor(m => m.Influence, "Influence"):</label></dt>
                        <dd>@Html.TextAreaFor(m => m.Influence)</dd>
                        <dd>@Html.ValidationMessageFor(m => m.Influence)</dd>

                        @*<dt> <label for="image_title_hires">@Html.LabelFor(m => m.Calender, "Calendar"):</label></dt>
                        <dd>@Html.TextAreaFor(m => m.Calender)</dd>
                        <dd>@Html.ValidationMessageFor(m => m.Calender)</dd>
                        <dd>&nbsp;</dd>*@

                        <dt> <label for="image_title_hires">@Html.LabelFor(m => m.SetUpRequirements, "Set Up Requirements"):</label></dt>
                        <dd>@Html.TextAreaFor(m => m.SetUpRequirements)</dd>
                        <dd>@Html.ValidationMessageFor(m => m.SetUpRequirements)</dd>
                        <dd>&nbsp;</dd>

                        <dt> <label for="image_title_hires">@Html.LabelFor(m => m.Tesimonials, "Tesimonials"):</label></dt>
                        <dd>@Html.TextAreaFor(m => m.Tesimonials)</dd>
                        <dd>@Html.ValidationMessageFor(m => m.Tesimonials)</dd>
                        <dd>&nbsp;</dd>

                        <dt> <label for="image_title_hires">@Html.LabelFor(m => m.Personal, "Personal"):</label></dt>
                        <dd>@Html.TextAreaFor(m => m.Personal)</dd>
                        <dd>@Html.ValidationMessageFor(m => m.Personal)</dd>
                        <dd>&nbsp;</dd>
                    </dl>
                </div>
            </div>

            <div class="upload" style="text-align:right;">
                <input type="submit" id="btnUpdate" name="infobutton" value="Update Details" />
            </div>
            <div class="clear"></div>
        </div>
    </div>


}