Artistwala_BB/ArtistWala/Areas/Admin/Controllers/SettingsController.cs
using ArtistWala.Areas.Admin.Models;
using ArtistWala.Common;
using ArtistWala.Repository;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ArtistWala.Areas.Admin.Controllers
{
    [CustomAuthorization(LoginPage = "~/Admin/Dashboard/AdminLogin")]
    public class SettingsController : Controller
    {
        ArtistWalaEntities context = new ArtistWalaEntities();
        CommonMethods objCommon = new CommonMethods();
        AESEncryption objEncrp = new AESEncryption();
        //
        // GET: /Admin/Settings/
        public ActionResult AddSettings(int id)
        {
            GeneralSettingModel obj = new GeneralSettingModel();
            try
            {
                if (!objCommon.IsPageAccessible())
                {
                    return RedirectToAction("Index", "Dashboard", new { Area = "Admin" });
                }

                tblGeneralSetting objSetting = context.tblGeneralSettings.Find(id);

                obj = new GeneralSettingModel()
                {
                    SMTPServer = objSetting.SMTPServer,
                    SMTPPort = (objSetting.SMTPPort ?? 0),
                    FromEmail = objSetting.FromEmail,
                    EmailPassword = objSetting.EmailPassword,
                    SSLSecurity = (objSetting.SSLSecurity ?? false),
                    SMSId = objSetting.SMSId,
                    SMSLink = objSetting.SMSLink,
                    SMSPassword = objSetting.SMSPassword,
                    MaxProfilePicSize = objSetting.MaxProfilePicSize ?? 0,
                    MaxPhotoSize = objSetting.MaxPhotoSize ?? 0,
                    MaxNoOfVideo = objSetting.MaxNoOfVideo ?? 0,
                    MaxNoOfPhoto = objSetting.MaxNoOfPhoto ?? 0,
                    MaxNoOfAudio = objSetting.MaxNoOfAudio ?? 0,
                    MaxCoverPicSize = objSetting.MaxCoverPicSize ?? 0,
                    MaxAudioSize = objSetting.MaxAudioSize ?? 0,
                    MobileVerification = (objSetting.MobileVerification ?? false),

                };

            }
            catch (Exception ex) { }

            return View(obj);
        }

        [HttpPost]
        public ActionResult AddSettings(GeneralSettingModel obj, int id)
        {
            try
            {
                if (!objCommon.IsPageAccessible())
                {
                    return RedirectToAction("Index", "Dashboard", new { Area = "Admin" });
                }

                tblGeneralSetting objSetting = context.tblGeneralSettings.Find(id);

                objSetting.SMTPServer = obj.SMTPServer;
                objSetting.SMTPPort = obj.SMTPPort;
                objSetting.FromEmail = obj.FromEmail;
                objSetting.EmailPassword = obj.EmailPassword;
                objSetting.SSLSecurity = obj.SSLSecurity;
                objSetting.SMSId = obj.SMSId;
                objSetting.SMSLink = obj.SMSLink;
                objSetting.SMSPassword = obj.SMSPassword;
                objSetting.MaxAudioSize = obj.MaxAudioSize;
                objSetting.MaxCoverPicSize = obj.MaxCoverPicSize;
                objSetting.MaxNoOfAudio = obj.MaxNoOfAudio;
                objSetting.MaxNoOfPhoto = obj.MaxNoOfPhoto;
                objSetting.MaxNoOfVideo = obj.MaxNoOfVideo;
                objSetting.MaxPhotoSize = obj.MaxPhotoSize;
                objSetting.MaxProfilePicSize = obj.MaxProfilePicSize;
                objSetting.SMSId = obj.SMSId;
                objSetting.MobileVerification = obj.MobileVerification;
                context.Entry(objSetting).State = EntityState.Modified;
                context.SaveChanges();
                ViewBag.Message = "The Setting has been successfully updated.";
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Sorry! Please try again later.";
            }
            return View(obj);
        }

        public ActionResult AddEmailTemplate(int id = 0)
        {
            EmailModel objEmail = new EmailModel();
            try
            {
                if (!objCommon.IsPageAccessible())
                {
                    return RedirectToAction("Index", "Dashboard", new { Area = "Admin" });
                }

                if (id > 0)
                {
                    tblEmailTemplate obj = context.tblEmailTemplates.Find(id);

                    objEmail = new EmailModel()
                    {
                        AddBCC = obj.AddBCC,
                        AddCC = obj.AddCC,
                        AssociatedTags = obj.AssociatedTags,
                        EmailBody = obj.EmailBody,
                        EmailSubject = obj.EmailSubject,
                        IsActive = (obj.IsActive ?? false),
                        TemplateId = obj.TemplateId,
                        TemplateName = obj.TemplateName
                    };
                }

            }
            catch (Exception ex) { }
            return View(objEmail);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddEmailTemplate(EmailModel obj, int id = 0)
        {
            try
            {
                if (!objCommon.IsPageAccessible())
                {
                    return RedirectToAction("Index", "Dashboard", new { Area = "Admin" });
                }

                tblEmailTemplate objEmail = context.tblEmailTemplates.Find(id);

                objEmail.AddBCC = obj.AddBCC;
                objEmail.AddCC = obj.AddCC;
                objEmail.AssociatedTags = obj.AssociatedTags;
                objEmail.EmailBody = obj.EmailBody;
                objEmail.EmailSubject = obj.EmailSubject;
                objEmail.IsActive = obj.IsActive;
                objEmail.TemplateName = obj.TemplateName;

                context.Entry(objEmail).State = EntityState.Modified;
                context.SaveChanges();
                ModelState.Clear();

                ViewBag.Message = "The Template has been successfully updated.";
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Sorry! Please try again later.";
            }
            return View();
        }

        public ActionResult AddSMSTemplate(int id = 0)
        {
            SMSModel objSMS = new SMSModel();
            try
            {
                if (!objCommon.IsPageAccessible())
                {
                    return RedirectToAction("Index", "Dashboard", new { Area = "Admin" });
                }

                if (id > 0)
                {
                    tblSMSTemplate obj = context.tblSMSTemplates.Find(id);

                    objSMS = new SMSModel()
                    {
                        TemplateId = obj.TemplateId,
                        TemplateName = obj.TemplateName,
                        SMSBody = obj.SMSBody,
                        IsActive = (obj.IsActive ?? false),
                    };
                }

            }
            catch (Exception ex) { }
            return View(objSMS);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult AddSMSTemplate(SMSModel obj, int id = 0)
        {
            try
            {
                if (!objCommon.IsPageAccessible())
                {
                    return RedirectToAction("Index", "Dashboard", new { Area = "Admin" });
                }

                tblSMSTemplate objSMS = context.tblSMSTemplates.Find(id);

                objSMS.TemplateName = obj.TemplateName;
                objSMS.SMSBody = obj.SMSBody;
                objSMS.IsActive = obj.IsActive;


                context.Entry(objSMS).State = EntityState.Modified;
                context.SaveChanges();
                ModelState.Clear();

                ViewBag.Message = "The Template has been successfully updated.";
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Sorry! Please try again later.";
            }
            return View();
        }

        public ActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePasswordModel objCP)
        {
            try
            {
                int UserId = default(int);
                var authCookie = Request.Cookies[FormsAuthentication.FormsCookieName];
                if (authCookie != null)
                {
                    var authTicket = FormsAuthentication.Decrypt(authCookie.Value);
                    int.TryParse(authTicket.UserData, out UserId);
                    // data is empty !!!
                }

                tblUser objUser = context.tblUsers.Find(UserId);

                if (objEncrp.DecryptPassword(objUser.Password) == objCP.OldPassword)
                {
                    objUser.Password = objEncrp.EncryptPassword(objCP.NewPassword);

                    context.Entry(objUser).State = EntityState.Modified;
                    context.SaveChanges();

                    var Modarators = context.tblModarators.Where(x => x.FK_UserId == UserId).FirstOrDefault();
                    string emailTo = string.Empty;
                    if (Modarators != null)
                    {
                        emailTo = Modarators.Email;
                    }

                    tblEmailTemplate email = context.tblEmailTemplates.Where(x => x.TemplateId == 4).FirstOrDefault();
                    string emailBody = email.EmailBody.Replace("@Name", objUser.Name).Replace("@Password", objEncrp.DecryptPassword(objUser.Password));
                    objCommon.sendMailInHtmlFormat(email.AddCC, emailTo, email.AddBCC, email.EmailSubject, emailBody);

                    ViewBag.Message = "Your password has been successfully updated.";
                }
                else
                {

Artistwala_BB/ArtistWala/Areas/Admin/Views/Settings/AddEmailTemplate.cshtml
@model ArtistWala.Areas.Admin.Models.EmailModel
@{
    ViewBag.Title = "Add Email Template";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<link href="/ckeditor/contents.css" rel="stylesheet" type="text/css">

<script src="/ckeditor/ckeditor.js"></script>
<script src="/ckeditor/adapters/jquery.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $('#TemplateName').change(function () {
            if ($('#TemplateName').val() == '') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 0 })';
            }
            if ($('#TemplateName').val() == 'Registration') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 1 })';
            }
            if ($('#TemplateName').val() == 'Welcome to Artistwala') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 2 })';
            }
            if ($('#TemplateName').val() == 'Password Recovery') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 3 })';
            }
            if ($('#TemplateName').val() == 'Change password') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 4 })';
            }
            if ($('#TemplateName').val() == 'Contact enquery') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 5 })';
            }
            if ($('#TemplateName').val() == 'Artist Contact Request') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 6 })';
            }
            if ($('#TemplateName').val() == 'Client Contact Request') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 7 })';
            }
            if ($('#TemplateName').val() == 'Artist Quote Request') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 8 })';
            }
            if ($('#TemplateName').val() == 'Client Quote Request') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 9 })';
            }
            if ($('#TemplateName').val() == 'Pending Review for Client') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 10 })';
            }
            if ($('#TemplateName').val() == 'Pending Review for Artist') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 11 })';
            }
            if ($('#TemplateName').val() == 'Submit Review for Artist') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 12 })';
            }
            if ($('#TemplateName').val() == 'Submit Review for Client') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 13 })';
            }
            if ($('#TemplateName').val() == 'Reply Message for Receiver') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 14 })';
            }
            if ($('#TemplateName').val() == 'Reply Message for Sender') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 15 })';
            }
        });
    });

</script>


@using (Html.BeginForm("AddEmailTemplate", "Settings", FormMethod.Post, new { Area = "Admin" }))
{
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Add Email Template</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="panel-heading">
                            <label class="control-label" style="color:green;">@ViewBag.Message</label>
                            <p class="help-block">@ViewBag.ErrorMessage</p>
                        </div>
                        <div class="col-lg-6">
                            <form role="form">
                                <div class="form-group">
                                    <label>Email Templates *</label>
                                    @Html.DropDownListFor(m => m.TemplateName, new List<SelectListItem>()
                                        {
                                            new SelectListItem() { Text= "Registration", Value = "Registration" },
                                            new SelectListItem() { Text= "Welcome to Artistwala", Value = "Welcome to Artistwala" },
                                            new SelectListItem() { Text= "Password Recovery", Value = "Password Recovery" },
                                            new SelectListItem() { Text= "Change password", Value = "Change password" },
                                            new SelectListItem() { Text= "Contact enquery", Value = "Contact enquery" },
                                            new SelectListItem() { Text= "Artist Contact Request", Value = "Artist Contact Request" },
                                            new SelectListItem() { Text= "Client Contact Request", Value = "Client Contact Request" },
                                            new SelectListItem() { Text= "Artist Quote Request", Value = "Artist Quote Request" },
                                            new SelectListItem() { Text= "Client Quote Request", Value = "Client Quote Request" },
                                            new SelectListItem() { Text= "Pending Review for Client", Value = "Pending Review for Client" },
                                            new SelectListItem() { Text= "Pending Review for Artist", Value = "Pending Review for Artist" },
                                            new SelectListItem() { Text= "Submit Review for Artist", Value = "Submit Review for Artist" },
                                            new SelectListItem() { Text= "Submit Review for Client", Value = "Submit Review for Client" },
                                            new SelectListItem() { Text= "Reply Message for Receiver", Value = "Reply Message for Receiver" },
                                            new SelectListItem() { Text= "Reply Message for Sender", Value = "Reply Message for Sender" }                                               
                                        }, "Select Template Name", new { @class = "form-control" })
                                    <p class="help-block">@Html.ValidationMessageFor(m => m.TemplateName)</p>
                                </div>
                                <div class="form-group">
                                    <label>Email Subject *</label>
                                    @Html.TextBoxFor(m => m.EmailSubject, new { @class = "form-control" })
                                    <p class="help-block">@Html.ValidationMessageFor(m => m.EmailSubject)</p>
                                </div>
                                <div class="form-group">
                                    <label>Email Body *</label>
                                    @Html.TextAreaFor(m => m.EmailBody, new { @class = "form-control ckeditor" })
                                    <p class="help-block">@Html.ValidationMessageFor(m => m.EmailBody)</p>
                                </div>
                                <div class="form-group">
                                    <label>Send Mail From</label>
                                    @Html.TextBoxFor(m => m.AddCC, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>BCC to</label>
                                    @Html.TextBoxFor(m => m.AddBCC, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Associated Tags</label>
                                    @Html.DisplayFor(m => m.AssociatedTags, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Is Active</label>
                                    @Html.CheckBoxFor(m => m.IsActive, new { @class = "form-control" })
                                </div>
                                <input type="submit" id="btnUploadImage" class="btn btn-default" value="Save" />
                            </form>
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
}

Artistwala_BB/ArtistWala/Areas/Admin/Views/Settings/AddEmailTemplate_bak.cshtml
@model ArtistWala.Areas.Admin.Models.EmailModel
@{
    ViewBag.Title = "Add Email Template";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<link href="/ckeditor/contents.css" rel="stylesheet" type="text/css">

<script src="/ckeditor/ckeditor.js"></script>
<script src="/ckeditor/adapters/jquery.js"></script>
<script type="text/javascript">

    $(document).ready(function () {
        $('#TemplateName').change(function () {
            if ($('#TemplateName').val() == '') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 0 })';
            }
            if ($('#TemplateName').val() == 'Registration') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 1 })';
            }
            if ($('#TemplateName').val() == 'Welcome to Artistwala') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 2 })';
            }
            if ($('#TemplateName').val() == 'Password Recovery') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 3 })';
            }
            if ($('#TemplateName').val() == 'Change password') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 4 })';
            }
            if ($('#TemplateName').val() == 'Contact enquery') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 5 })';
            }
            if ($('#TemplateName').val() == 'Artist Contact Request') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 6 })';
            }
            if ($('#TemplateName').val() == 'Client Contact Request') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 7 })';
            }
            if ($('#TemplateName').val() == 'Artist Quote Request') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 8 })';
            }
            if ($('#TemplateName').val() == 'Client Quote Request') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 9 })';
            }
            if ($('#TemplateName').val() == 'Pending Review') {
                window.location.href = '@Url.Action("AddEmailTemplate", "Settings", new { id = 10 })';
            }
        });
    });

</script>


@using (Html.BeginForm("AddEmailTemplate", "Settings", FormMethod.Post, new { Area = "Admin" }))
{
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Add Email Template</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="panel-heading">
                            <label class="control-label" style="color:green;">@ViewBag.Message</label>
                            <p class="help-block">@ViewBag.ErrorMessage</p>
                        </div>
                        <div class="col-lg-6">
                            <form role="form">
                                <div class="form-group">
                                    <label>Email Templates *</label>
                                    @Html.DropDownListFor(m => m.TemplateName, new List<SelectListItem>()
                                        {
                                            new SelectListItem() { Text= "Registration", Value = "Registration" },
                                            new SelectListItem() { Text= "Welcome to Artistwala", Value = "Welcome to Artistwala" },
                                            new SelectListItem() { Text= "Password Recovery", Value = "Password Recovery" },
                                            new SelectListItem() { Text= "Change password", Value = "Change password" },
                                            new SelectListItem() { Text= "Contact enquery", Value = "Contact enquery" },
                                            new SelectListItem() { Text= "Artist Contact Request", Value = "Artist Contact Request" },
                                            new SelectListItem() { Text= "Client Contact Request", Value = "Client Contact Request" },
                                            new SelectListItem() { Text= "Artist Quote Request", Value = "Artist Quote Request" },
                                            new SelectListItem() { Text= "Client Quote Request", Value = "Client Quote Request" },
                                            new SelectListItem() { Text= "Pending Review", Value = "Pending Review" }                                           
                                        }, "Select Template Name", new { @class = "form-control" })
                                    <p class="help-block">@Html.ValidationMessageFor(m => m.TemplateName)</p>
                                </div>
                                <div class="form-group">
                                    <label>Email Subject *</label>
                                    @Html.TextBoxFor(m => m.EmailSubject, new { @class = "form-control" })
                                    <p class="help-block">@Html.ValidationMessageFor(m => m.EmailSubject)</p>
                                </div>
                                <div class="form-group">
                                    <label>Email Body *</label>
                                    @Html.TextAreaFor(m => m.EmailBody, new { @class = "form-control ckeditor" })
                                    <p class="help-block">@Html.ValidationMessageFor(m => m.EmailBody)</p>
                                </div>
                                <div class="form-group">
                                    <label>Send Mail From</label>
                                    @Html.TextBoxFor(m => m.AddCC, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>BCC to</label>
                                    @Html.TextBoxFor(m => m.AddBCC, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Associated Tags</label>
                                    @Html.DisplayFor(m => m.AssociatedTags, new { @class = "form-control" })
                                </div>
                                <div class="form-group">
                                    <label>Is Active</label>
                                    @Html.CheckBoxFor(m => m.IsActive, new { @class = "form-control" })
                                </div>
                                <input type="submit" id="btnUploadImage" class="btn btn-default" value="Save" />
                            </form>
                        </div>
                        <!-- /.col-lg-6 (nested) -->
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
}

Artistwala_BB/ArtistWala/Areas/Admin/Views/Settings/AddSettings.cshtml
@model ArtistWala.Areas.Admin.Models.GeneralSettingModel
@{
    ViewBag.Title = "Add Settings";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<script type="text/javascript" src="/js/common.js"></script>

@using (Html.BeginForm("AddSettings", "Settings", FormMethod.Post, new { Area = "Admin" }))
{
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">@ViewBag.Title</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="panel-heading">
                <label class="control-label" style="color:green;">@ViewBag.Message</label>
                <p class="help-block">@ViewBag.ErrorMessage</p>
            </div>
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">

                            <form role="form">
                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>@Html.LabelFor(m => m.SMTPServer) *</label>
                                        @Html.TextBoxFor(m => m.SMTPServer, new { @class = "form-control" })
                                        <p class="help-block">@Html.ValidationMessageFor(m => m.SMTPServer)</p>
                                    </div>
                                    <div class="form-group">
                                        <label>@Html.LabelFor(m => m.SMTPPort) *</label>
                                        @Html.TextBoxFor(m => m.SMTPPort, new { @class = "form-control", onkeypress = "return checkOnlyNumber(this,event);" })
                                        <p class="help-block">@Html.ValidationMessageFor(m => m.SMTPPort)</p>
                                    </div>
                                    <div class="form-group">
                                        <label>@Html.LabelFor(m => m.FromEmail)</label>
                                        @Html.TextBoxFor(m => m.FromEmail, new { @class = "form-control" })
                                        <p class="help-block">@Html.ValidationMessageFor(m => m.FromEmail)</p>
                                    </div>
                                    <div class="form-group">
                                        <label>@Html.LabelFor(m => m.EmailPassword)</label>
                                        @Html.TextBoxFor(m => m.EmailPassword, new { @class = "form-control" })
                                    </div>
                                    <div class="form-group">
                                        <label>@Html.LabelFor(m => m.SSLSecurity)</label>
                                        @Html.CheckBoxFor(m => m.SSLSecurity)
                                    </div>
                                    <div class="form-group">
                                        <label>@Html.LabelFor(m => m.MobileVerification)</label>
                                        @Html.CheckBoxFor(m => m.MobileVerification)
                                    </div>
                                    <button type="submit" class="btn btn-default">Save</button>
                                </div>

                                <div class="col-lg-6">
                                    <div class="form-group">
                                        <label>SMS SID *</label>
                                        @Html.TextBoxFor(m => m.SMSId, new { @class = "form-control" })
                                        <p class="help-block">@Html.ValidationMessageFor(m => m.SMSId)</p>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label>SMS User Id *</label>
                                        @Html.TextBoxFor(m => m.SMSLink, new { @class = "form-control" })
                                        <p class="help-block">@Html.ValidationMessageFor(m => m.SMSLink)</p>
                                    </div>

                                    <div class="form-group">
                                        <label>@Html.LabelFor(m => m.SMSPassword) *</label>
                                        @Html.PasswordFor(m => m.SMSPassword, new { @class = "form-control" })
                                        <p class="help-block">@Html.ValidationMessageFor(m => m.SMSPassword)</p>
                                    </div>

                                    

                                    
                                </div>
                            </form>
                             

                            <!-- /.col-lg-6 (nested) -->
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
        </div>
    </div>
}